name: CI - PHPUnit Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1' 
        extensions: mbstring, dom, curl, gd, sqlite3
        coverage: none

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Run PHPUnit tests with coverage
      run: ./vendor/bin/phpunit --coverage-clover=coverage.clover

    - name: Upload Coverage Report
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage
        path: coverage.clover

    - name: Generate Cobertura Report
      run: |
        php ./vendor/bin/phpcov merge --clover coverage.clover
        php ./vendor/bin/phpcov html
        php ./vendor/bin/phpcov xml --coverage-clover coverage.xml
      env:
        PHPCOV_PATH: ./vendor/bin/phpcov

    - name: Upload Cobertura Coverage Report
      uses: actions/upload-artifact@v3
      with:
        name: cobertura-coverage
        path: coverage.xml

    - name: Code Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: coverage/**/coverage.cobertura.xml
        badge: true
        fail_below_min: true
        format: markdown
        hide_branch_rate: false
        hide_complexity: true
        indicators: true
        output: both
        thresholds: '60 80'
