name: CI - PHPUnit Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1' 
        extensions: mbstring, dom, curl, gd, sqlite3, xmlwriter
        coverage: xdebug

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Run PHPUnit tests with Cobertura coverage
      run: ./vendor/bin/phpunit --coverage-cobertura=coverage.xml

    - name: Upload Cobertura Coverage Report
      uses: actions/upload-artifact@v3
      with:
        name: cobertura-coverage
        path: coverage.xml

    - name: Code Coverage Report Summary
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: coverage.xml
        badge: true
        fail_below_min: true
        format: markdown
        hide_branch_rate: false
        hide_complexity: true
        indicators: true
        output: file
        thresholds: '60 80'

    - name: Display coverage results
      run: |
        echo "## Code Coverage Results" >> $GITHUB_STEP_SUMMARY
        cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY

   - name: Run PHPCS
     run: ./vendor/bin/phpcs --extensions=php ./lib/

   - name: Run PHPMD
     run: ./vendor/bin/phpmd ./lib ansi codesize,unusedcode, naming

   - name: Run PHPStan
     run: ./vendor/bin/phpstan analyse lib
